name: Release Charts

on:
  push:
    branches:
      - main

# on:
#   pull_request:
#     types: [closed]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: nginx
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"